//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDP.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BDP.Application.ErrorResource", typeof(ErrorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account handler exception.
        /// </summary>
        public static string AddAccountHandlerError {
            get {
                return ResourceManager.GetString("AddAccountHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user handler exception.
        /// </summary>
        public static string AddUserHandlerError {
            get {
                return ResourceManager.GetString("AddUserHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null.
        /// </summary>
        public static string Cannot_Be_Empty {
            get {
                return ResourceManager.GetString("Cannot_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check balance handler error.
        /// </summary>
        public static string CheckBalanceHandlerError {
            get {
                return ResourceManager.GetString("CheckBalanceHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user handler exception.
        /// </summary>
        public static string DeleteUserHandlerError {
            get {
                return ResourceManager.GetString("DeleteUserHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit handler exception.
        /// </summary>
        public static string DepositHandlerError {
            get {
                return ResourceManager.GetString("DepositHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address has already account.
        /// </summary>
        public static string EmailAddress_HasAccount {
            get {
                return ResourceManager.GetString("EmailAddress_HasAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string EmailAddress_Invalid {
            get {
                return ResourceManager.GetString("EmailAddress_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address that you entered doesn&apos;t match any account.
        /// </summary>
        public static string EmailAddress_Invalid_NotMatch {
            get {
                return ResourceManager.GetString("EmailAddress_Invalid_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get users handler exception.
        /// </summary>
        public static string GetUsersHandlerError {
            get {
                return ResourceManager.GetString("GetUsersHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds in your account.
        /// </summary>
        public static string Insufficient_Balance {
            get {
                return ResourceManager.GetString("Insufficient_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account Number.
        /// </summary>
        public static string InvalidAccountNumber {
            get {
                return ResourceManager.GetString("InvalidAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login handler command exception.
        /// </summary>
        public static string LoginHandlerCommand {
            get {
                return ResourceManager.GetString("LoginHandlerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address and password do not match.
        /// </summary>
        public static string Password_NotMatch_Email {
            get {
                return ResourceManager.GetString("Password_NotMatch_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer handler error.
        /// </summary>
        public static string TransferHandleError {
            get {
                return ResourceManager.GetString("TransferHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user handler exception.
        /// </summary>
        public static string UpdateUserHandlerError {
            get {
                return ResourceManager.GetString("UpdateUserHandlerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exist.
        /// </summary>
        public static string User_AlreadyExist {
            get {
                return ResourceManager.GetString("User_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string User_NotExist {
            get {
                return ResourceManager.GetString("User_NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw handler exception.
        /// </summary>
        public static string WithdrawHandlerError {
            get {
                return ResourceManager.GetString("WithdrawHandlerError", resourceCulture);
            }
        }
    }
}
